services:
  - type: web
    name: ksm-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:socket_app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ksm-db
          property: connectionString
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        value: ksm.tutorials@ucc.edu.gh
      - key: ADMIN_USERNAME
        value: admin
    plan: free